---
title: "PS05"
author: "Michael Wethington"
date: "9/23/2020"
output: pdf_document
---

**Metropolis Sampler**

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(boot)

#Choose Starting Values
df <- read.csv("C:/Users/wmichael/Google Drive/BEE569/labs/l5/data/plants.csv")

current_b0 <- rnorm(1, 0, 1)
current_b1 <- rnorm(1, 0, 1)

b0_accepted <- c()
b1_accepted <- c()


N = 1000
step_sigma <- .14

#Scale the elevation 
df$Elevation <- scale(df$Elevation)

for(i in 1:N){
  
  
  next_b0 <- current_b0+rnorm(1, 0, step_sigma)
  next_b1 <- current_b1+rnorm(1, 0, step_sigma)
  
  accept_probability <- sum(dbinom(df$PlantEnd, df$Plants, inv.logit(next_b0 + next_b1 * df$Elevation), log = T)) +
                              dnorm(next_b0, 0, 1, log = T) + dnorm(next_b1, 0, 1, log=T) -
                              
                              sum(dbinom(df$PlantEnd, df$Plants, inv.logit(current_b0 + current_b1 * df$Elevation), log = T)) -
                              dnorm(current_b0, 0, 1, log =T) - dnorm(current_b1, 0,1,log=T)
  
  
  if(accept_probability > runif(1,0,1)){
    
    b0_accepted <- c(b0_accepted, next_b0)
    b1_accepted <- c(b1_accepted, next_b1)
  }
  
}


plot(b0_accepted, b1_accepted)

```





**Gibbs Sampler**

```{r cars}

# initialize vectors to store 
mu <- c()
tau <- c()


gibbs.dat <- read.csv("C:/Users/wmichael/Google Drive/BEE569/labs/l5/data/gibbs.csv")

names(gibbs.dat)[names(gibbs.dat) == "X2.8"] <- "vector"
gibbs.dat


gamma <- 1
omega_square <- 0.16
alpha <- 0.1
beta <- 0.1

mu[1] <- rnorm(n = 1,mean=gamma,omega_square)# Mu
tau[1] <- rgamma(1,alpha,beta) # Tau

# number of iterations
n.iter <- 10000

# starting values (index starting at 1, not 0)
#mu[1] <- runif(1, 0, 1)
#tau[1] <- runif(1, 0, 1)

# iterate through and sample
for (t in 2:n.iter){
  
  mu[t] <- rnorm(n = 1, ((tau[t-1]*sum(gibbs.dat$vector))+(gamma/omega_square))/(length(gibbs.dat$vector)*tau[t-1]+(1/omega_square)), 
  1/((length(gibbs.dat$V1)*tau[t-1])+(1/omega_square))) # update  dependent on x[t-1]
  
  
  tau[t] <- rgamma(1, (alpha + 0.5*length(gibbs.dat$vector)), (beta + 0.5*(sum(((gibbs.dat$vector-mu[t])^2))))) 

  }


# scatterplot of bivariate (x,) pairs
plot(mu, tau)
# histogram of marginal distribution for x
# marginalized out mu
hist(mu, breaks = 20)
# histogram of marginal distribution for 
# marginalized out tau
hist(tau, breaks = 20)


```
